# Generated by Django 3.2.4 on 2021-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210317_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_admin', 'Can manage users and restaurants.')]},
        ),
    ]
